// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Account struct {
	ID    int64  `db:"id" json:"id"`
	Owner string `db:"owner" json:"owner"`
	// decimal类型，精确小数
	Balance string `db:"balance" json:"balance"`
	// 货币类型
	Currency  string    `db:"currency" json:"currency"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// 取/存款记录
type Entry struct {
	ID        int64 `db:"id" json:"id"`
	AccountID int64 `db:"account_id" json:"account_id"`
}

type Transaction struct {
	ID        int64     `db:"id" json:"id"`
	From      int64     `db:"from" json:"from"`
	To        int64     `db:"to" json:"to"`
	Amount    string    `db:"amount" json:"amount"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
