// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
  account_id,
  transfer_id,
  amount,
  entry_type,
  currency,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, account_id, transfer_id, amount, entry_type, currency, created_at
`

type CreateEntryParams struct {
	AccountID  int64          `db:"account_id" json:"account_id"`
	TransferID sql.NullInt64  `db:"transfer_id" json:"transfer_id"`
	Amount     string         `db:"amount" json:"amount"`
	EntryType  sql.NullString `db:"entry_type" json:"entry_type"`
	Currency   string         `db:"currency" json:"currency"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.AccountID,
		arg.TransferID,
		arg.Amount,
		arg.EntryType,
		arg.Currency,
		arg.CreatedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransferID,
		&i.Amount,
		&i.EntryType,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
