// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer.sql

package db

import (
	"context"
	"time"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
  "from",
  "to",
  amount,
  created_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, "from", "to", amount, instruction, created_at
`

type CreateTransferParams struct {
	From      int64     `db:"from" json:"from"`
	To        int64     `db:"to" json:"to"`
	Amount    string    `db:"amount" json:"amount"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.From,
		arg.To,
		arg.Amount,
		arg.CreatedAt,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.To,
		&i.Amount,
		&i.Instruction,
		&i.CreatedAt,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :many
SELECT id, "from", "to", amount, instruction, created_at FROM transfers
WHERE "from" = $1 OR "to" = $1
`

func (q *Queries) GetTransfer(ctx context.Context, from int64) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, getTransfer, from)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.From,
			&i.To,
			&i.Amount,
			&i.Instruction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
